
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SentimentModel.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SentimentModel.ModelInput sampleData = new SentimentModel.ModelInput()
            {
                SentimentText = @"==RUDE== Dude, you are rude upload that carl picture back, or else.",
                LoggedIn = true,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = SentimentModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Sentiment with predicted Sentiment from sample data...\n\n");


            Console.WriteLine($"Sentiment: {1F}");
            Console.WriteLine($"SentimentText: {@"==RUDE== Dude, you are rude upload that carl picture back, or else."}");
            Console.WriteLine($"LoggedIn: {true}");


            Console.WriteLine($"\n\nPredicted Sentiment: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
